In [1]:
#1)
#----- YOUR CODE HERE -----
import numpy as np
count = int(input())
array = np.arange(count)
#--------------------------
print("Массив до значения,задаваемая вами",array)


Массив до значения,задаваемая вами [0 1 2 3 4]


In [2]:
#2)
#----- YOUR CODE HERE -----
import numpy as np
array_zero = np.array([0]*5)
array_one = np.array([1]*10)
#--------------------------
print("Массив из 0:\n",array_zero)
print("Массив из 1:\n",array_one)

Массив из 0:
 [0 0 0 0 0]
Массив из 1:
 [1 1 1 1 1 1 1 1 1 1]


In [3]:
#3)
#----- YOUR CODE HERE -----
import numpy as np
count = int(input())
#--------------------------
print("2D массив где по диагонали присвоено значение Pi:\n",np.diag([np.pi]*count))

2D массив где по диагонали присвоено значение Pi:
 [[3.14159265 0.         0.         0.         0.        ]
 [0.         3.14159265 0.         0.         0.        ]
 [0.         0.         3.14159265 0.         0.        ]
 [0.         0.         0.         3.14159265 0.        ]
 [0.         0.         0.         0.         3.14159265]]


In [6]:
#4)
#----- YOUR CODE HERE -----
import numpy as np
count = int(input())
matrix = np.full((count,count),False)
#--------------------------
print("2D массив ,заполненный значением FALSE:\n",matrix,"\nТип переменной:",)
type(matrix[0,0])

2D массив ,заполненный значением FALSE:
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]] 
Тип переменной:


numpy.bool_

In [5]:
#5)
#----- YOUR CODE HERE -----
import numpy as np
array = np.arange(16)
new_array = np.copy(array)
for i in range(16):
    if(new_array[i] % 2 == 0):
        new_array[i] = 42
#--------------------------
# ИСХОДНЫЙ МАССИВ
print("Исходный массив:\n",array)
# НОВЫЙ МАССИВ
print("Новый массив:\n",new_array)

Исходный массив:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Новый массив:
 [42  1 42  3 42  5 42  7 42  9 42 11 42 13 42 15]


In [7]:
#6) 
#----- YOUR CODE HERE -----
import numpy as np
count_one = 0
index = 0
array_index=[]
array = np.random.randint(2 ,size=15)
#array = np.array([1]*15)
for i in range(15):
    if(array[i] == 1):
        count_one=count_one+1
        array_index.append(i)
#--------------------------
# ИСХОДНЫЙ МАССИВ
print("Исходный массив:\n",array)
# ИНДЕКСЫ
print("Индексы где находятся 1:\n",array_index)
# КОЛИЧЕСТВО
print("Количество 1:\n",count_one)

Исходный массив:
 [0 0 0 1 0 0 1 0 1 0 1 1 0 0 1]
Индекды где находяться 1:
 [3, 6, 8, 10, 11, 14]
Количество 1:
 6


In [12]:
#7) 
#----- YOUR CODE HERE -----
import numpy as np
x3 = np.random.random((2,3, 4))
#--------------------------
print("Размерность: ",x3.ndim)
print("Количество элементов вдоль каждой размерности:",x3.shape)
print("Количество элементов в массиве:",x3.size)

Размерность:  3
Количество элементов вдоль каждой размерности: (2, 3, 4)
Количество элементов в массиве: 24


In [8]:
#8)
#----- YOUR CODE HERE -----
import numpy as np
array = np.arange(9)
new_array = np.copy(array).reshape(3,3) 
#--------------------------
# ИСХОДНЫЙ МАССИВ
print("Исходный массив:\n",array)
# НОВЫЙ МАССИВ
print("Новый массив:\n",new_array)



Исходный массив:
 [0 1 2 3 4 5 6 7 8]
Новый массив:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#9)
#----- YOUR CODE HERE -----
import numpy as np
def func(array,row,col):
    if(row < np.size(array,0) or col<np.size(array,1)):
        row_sum = (array[row]).sum()
        col_sum = (array[0:(np.size(array, 0)),col]).sum()
        list = tuple([row_sum,col_sum])
        return list
    else:
        print("error")
array = np.random.randint(10, size=(4, 4))
print("Введите строку,чтобы её суммировать:")
row = int(input())
print(row)
print("Введите колонку,чтобы её суммировать:")
col = int(input())
print(col)
#--------------------------
print("2D массив:\n",array)
print(func(array,row,col))

Введите строку,чтобы её суммировать:
4
Введите колонку,чтобы её суммировать:
4
2D массив:
 [[7 2 8 8]
 [2 7 2 9]
 [0 5 8 6]
 [7 2 8 3]]
error
None


In [13]:
#10)
#----- YOUR CODE HERE -----
import numpy as np
def mat_mul(matrix1,matrix2):
    list = []
    if (np.size(matrix1, 1)==np.size(matrix2, 0)):
        for i in range(np.size(matrix1, 0)):
            for j in range(np.size(matrix2, 1)):
                list.append((matrix1[i]*matrix2[0:(np.size(array, 0)),j]).sum())
        list = (np.copy(list)).reshape((np.size(matrix1, 0)),(np.size(matrix2, 1)))
        return list
    else:
        print("inner dimensions does not match")

matrix1 = np.random.randint(10, size=(7, 4))
matrix2 = np.random.randint(10, size=(4, 7))
#--------------------------
print("A:\n",matrix1,"\n")
print("B:\n",matrix2,"\n")
print("Произведение матриц A*B:\n",mat_mul(matrix1,matrix2))

A:
 [[2 8 6 5]
 [8 5 5 9]
 [0 4 1 1]
 [8 6 2 5]
 [3 9 3 7]
 [0 1 5 4]
 [7 0 6 7]] 

B:
 [[3 6 8 0 7 7 2]
 [2 1 5 4 0 6 3]
 [3 4 2 5 2 6 2]
 [7 3 0 0 2 0 1]] 

Произведение матриц A*B:
 [[ 75  59  68  62  36  98  45]
 [112 100  99  45  84 116  50]
 [ 18  11  22  21   4  30  15]
 [ 77  77  98  34  70 104  43]
 [ 85  60  75  51  41  93  46]
 [ 45  33  15  29  18  36  17]
 [ 88  87  68  30  75  85  33]]


In [16]:
#11)
#----- YOUR CODE HERE -----
import numpy as np
array = np.random.random(10)
max = array.max()
min = array.min()
mean = array.mean()
median = np.median(array)
#--------------------------
print(array)
print("Max value: %.3f\n\
Min value: %.3f\n\
Mean value: %.3f\n\
Median value: %.3f\n" % (max,min,mean,median))


[0.43177915 0.233412   0.11303712 0.41686081 0.00767863 0.23474754
 0.43167564 0.80916381 0.66357446 0.61406637]
Max value: 0.809
Min value: 0.008
Mean value: 0.396
Median value: 0.424



In [9]:
#11)
#----- YOUR CODE HERE -----
import numpy as np
def comp_dist(array_one,array_two):
    result = np.sqrt(((array_one - array_two)**2).sum())
    return result
array_one = np.random.randint(10, size=(6))
array_two = np.random.randint(10, size=(6))
#--------------------------
print("Разность Евклидового расстояния между своей функцией и библиотечной:",np.linalg.norm(array_one-array_two) - comp_dist(array_one,array_two))
print("Евклидово расстояние:",comp_dist(array_one,array_two))

Разность Евклидового расстояния между своей функцией и библеотечной: 0.0
Евклидово расстояние: 10.198039027185569
